version: '3.8'

services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - app-network
      
  user-service:
    build: ./user-service
    container_name: user-service
    ports:
      - "3001:3001"
    env_file:
      - .env
    depends_on:
      - postgres
      - rabbitmq
    networks:
      - app-network

  notification-service:
    build: ./notification-service
    container_name: notification-service
    ports:
      - "3002:3002"
    env_file:
      - .env
    depends_on:
      - redis
      - rabbitmq
    networks:
      - app-network

  postgres:
    image: postgres:15
    container_name: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: users_db
    networks:
      - app-network

  redis:
    image: redis:7
    container_name: notification-redis
    ports:
      - "6379:6379"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
